"""SQLAlchemy ORM models for digital medical prescriptions."""

from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import JSON, ForeignKey, Index, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.modules.auth.models import User
    from app.modules.consultations.models import Consultation
    from app.modules.doctors.models import Doctor


class Prescription(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Digital prescription generated by a doctor for a completed consultation."""

    __tablename__ = "prescriptions"

    consultation_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("consultations.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    doctor_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("doctors.id"),
        nullable=False,
        index=True,
    )
    patient_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )
    diagnosis: Mapped[str] = mapped_column(Text, nullable=False)
    medications: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB().with_variant(JSON(), "sqlite"), default=list, nullable=False
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (Index("idx_prescriptions_patient_created", "patient_id", "created_at"),)

    # Relationships
    consultation: Mapped["Consultation"] = relationship(
        "Consultation", back_populates="prescription"
    )
    doctor: Mapped["Doctor"] = relationship("Doctor")
    patient: Mapped["User"] = relationship("User")
